In [1]:
import numpy as np

In [2]:
# creating arrays using numpy
kanto = np.array([73,67,43])

In [3]:
kanto

array([73, 67, 43])

In [4]:
w1, w2, w3 = [0.3,0.2,0.5]

In [5]:
weights = np.array([w1,w2,w3])

In [6]:
weights

array([0.3, 0.2, 0.5])

In [7]:
# checking the type of these numpy arrays
type(weights)

numpy.ndarray

In [8]:
# Numpy arrays support the indexing notation
weights[0]

0.3

In [9]:
# finding the dot product of the arrays above
np.dot(kanto, weights)

56.8

In [10]:
# the dot operator functionality can be simplified by using * operator and calling the sum function on them
(kanto*weights).sum()

56.8

In [ ]:
# The * operator performs an element-wise multiplication of two arrays(assuming they have the same size)
# and the sum method calculates the sum of numbers in an array

In [11]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [12]:
(arr1*arr2).sum()

32

In [13]:
# Multi Dimensional Arrays (Matrices)
climate_data = np.array([[7,67,43],[91,88,64],[87,143,58],[102,43,37],[69,96,70]])

In [14]:
climate_data

array([[  7,  67,  43],
       [ 91,  88,  64],
       [ 87, 143,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [15]:
# getting to know the shape of the array
climate_data.shape

(5, 3)

In [16]:
weights

array([0.3, 0.2, 0.5])

In [17]:
weights.shape

(3,)

In [18]:
# 3D Array
arr3 = np.array([
    [[11, 12, 13], [13, 14, 15]],
    [[15, 16, 17], [17, 18, 19]]
                ])

In [19]:
arr3

array([[[11, 12, 13],
        [13, 14, 15]],

       [[15, 16, 17],
        [17, 18, 19]]])

In [20]:
arr3.shape


(2, 2, 3)

In [21]:
# all the elements in a numpy array should have the same datatype.

# checking the data type of a numpy array
weights.dtype

dtype('float64')

In [22]:
climate_data.dtype

dtype('int32')

In [23]:
climate_data


array([[  7,  67,  43],
       [ 91,  88,  64],
       [ 87, 143,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [ ]:
# the climate data is matrix. That is, it is a multi dimensional array
# weights is a single dimensional array. That is, it is a vector.
# we can do a matrix multiplication of matrices and vectors

In [24]:
# matrix multiplication
np.matmul(climate_data, weights)

array([37. , 76.9, 83.7, 57.7, 74.9])

In [25]:
# the @ opertator can be used to simply do matrix multiplication
climate_data @ weights

array([37. , 76.9, 83.7, 57.7, 74.9])