In [1]:
import numpy as np

In [2]:
arr2 = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 1, 2, 3]])

In [3]:
arr3 = np.array([[11, 12, 13, 14],
                [15, 16, 17, 18],
                [19, 20, 21, 22]])

In [4]:
# element wise operation. Addition, subtraction and multiplication can be performed on different arrays
arr2+arr3

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 21, 23, 25]])

In [5]:
# adding a scalar to the array
arr2 + 3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12,  4,  5,  6]])

In [6]:
arr4 = np.array([4, 5, 6, 7])

In [7]:
arr4.shape

(4,)

In [8]:
# now let us work with an array of different shape as the above
arr2.shape

(3, 4)

In [9]:
# since these two arrays have different shapes, it can be deduced that certain operations should not be performed on it
# but that is not the case here, since they are compatible
arr2+arr4

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

In [10]:
arr4+arr2

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

In [ ]:
# the above computations signify that the addititon operator is commutative 
# with respect to matrix

In [11]:
arr5 = np.array([7,8])

In [12]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 2, 3]])

In [13]:
arr2 + arr5

ValueError: operands could not be broadcast together with shapes (3,4) (2,) 

In [14]:
# Comparison Operators In Numpy Arrays
arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[2, 2, 3], [1, 2, 5]])

In [15]:
arr1 == arr2

array([[False,  True,  True],
       [False, False,  True]])

In [16]:
arr1 != arr2

array([[ True, False, False],
       [ True,  True, False]])

In [17]:
arr1 >= arr2

array([[False,  True,  True],
       [ True,  True,  True]])

In [18]:
arr1 < arr2

array([[ True, False, False],
       [False, False, False]])

In [19]:
# using the sum method, count the number of equal elements in two arrays
( arr1 == arr2).sum()

3