In [1]:
import numpy as np

In [2]:
arr1 = np.array([
    [[11, 12, 13, 14],
    [13, 14, 15, 19]],
    
    [[15, 16, 17, 21],
    [63, 92, 36, 18]],
    
    [[98, 32, 81, 23],
    [17, 18, 19.5, 43]]
])

In [3]:
arr1.shape

(3, 2, 4)

In [5]:
# Single element
arr1[1, 1, 2]

36.0

In [6]:
arr1

array([[[11. , 12. , 13. , 14. ],
        [13. , 14. , 15. , 19. ]],

       [[15. , 16. , 17. , 21. ],
        [63. , 92. , 36. , 18. ]],

       [[98. , 32. , 81. , 23. ],
        [17. , 18. , 19.5, 43. ]]])

In [9]:
# subarray using ranges
arr1[1:, 0:1, :2]

array([[[15., 16.]],

       [[98., 32.]]])

In [11]:
# mixing indices and ranges
arr1[1:, 1, :3]

array([[63. , 92. , 36. ],
       [17. , 18. , 19.5]])

In [12]:
arr1[1]

array([[15., 16., 17., 21.],
       [63., 92., 36., 18.]])