In [1]:
import numpy as np

In [2]:
# All zeros -- Null Matrix
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
# All ones
np.ones([2, 2, 3])

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [4]:
# Identity Matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
# Random vector
np.random.rand(5)

array([0.86092117, 0.6882535 , 0.10795129, 0.07475299, 0.43063246])

In [6]:
# Random matrix
np.random.rand(2, 3)

array([[0.23133019, 0.46017918, 0.12515852],
       [0.78332613, 0.62484793, 0.11409431]])

In [7]:
# Fixed Value
np.full([2, 3], 42)

array([[42, 42, 42],
       [42, 42, 42]])

In [8]:
# range with start, end and stop
np.arange(10, 90, 3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [9]:
# reshaping an array
np.arange(10, 90, 3).reshape(3, 3, 3)

array([[[10, 13, 16],
        [19, 22, 25],
        [28, 31, 34]],

       [[37, 40, 43],
        [46, 49, 52],
        [55, 58, 61]],

       [[64, 67, 70],
        [73, 76, 79],
        [82, 85, 88]]])

In [10]:
# equally spaced numbers in a range
np.linspace(3, 27, 12)

array([ 3.        ,  5.18181818,  7.36363636,  9.54545455, 11.72727273,
       13.90909091, 16.09090909, 18.27272727, 20.45454545, 22.63636364,
       24.81818182, 27.        ])